config/routes.rb
CantinhoDoAlergico::Application.routes.draw do
  resources :products

  resources :send_types

  resources :manufacturers

  resources :intolerance_types

  resources :sub_categories

  resources :categories

  resources :allergy_types

  root :to => 'products#index'

end

app/controllers/allergy_types_controller.rb
class AllergyTypesController < ApplicationController
  # GET /allergy_types
  # GET /allergy_types.json
  def index
    @allergy_types = AllergyType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @allergy_types }
    end
  end

  # GET /allergy_types/1
  # GET /allergy_types/1.json
  def show
    @allergy_type = AllergyType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @allergy_type }
    end
  end

  # GET /allergy_types/new
  # GET /allergy_types/new.json
  def new
    @allergy_type = AllergyType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @allergy_type }
    end
  end

  # GET /allergy_types/1/edit
  def edit
    @allergy_type = AllergyType.find(params[:id])
  end

  # POST /allergy_types
  # POST /allergy_types.json
  def create
    @allergy_type = AllergyType.new(params[:allergy_type])

    respond_to do |format|
      if @allergy_type.save
        format.html { redirect_to @allergy_type, notice: 'Allergy type was successfully created.' }
        format.json { render json: @allergy_type, status: :created, location: @allergy_type }
      else
        format.html { render action: "new" }
        format.json { render json: @allergy_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /allergy_types/1
  # PUT /allergy_types/1.json
  def update
    @allergy_type = AllergyType.find(params[:id])

    respond_to do |format|
      if @allergy_type.update_attributes(params[:allergy_type])
        format.html { redirect_to @allergy_type, notice: 'Allergy type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @allergy_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allergy_types/1
  # DELETE /allergy_types/1.json
  def destroy
    @allergy_type = AllergyType.find(params[:id])
    @allergy_type.destroy

    respond_to do |format|
      format.html { redirect_to allergy_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/allergy_types_helper.rb
module AllergyTypesHelper
end

app/views/allergy_types/_form.html.erb
<%= form_for(@allergy_type) do |f| %>
  <% if @allergy_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@allergy_type.errors.count, "error") %> prohibited this allergy_type from being saved:</h2>

      <ul>
      <% @allergy_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/allergy_types/edit.html.erb
<h1>Editing allergy_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @allergy_type %> |
<%= link_to 'Back', allergy_types_path %>

app/views/allergy_types/index.html.erb
<h1>Listing allergy_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @allergy_types.each do |allergy_type| %>
  <tr>
    <td><%= allergy_type.name %></td>
    <td><%= allergy_type.description %></td>
    <td><%= link_to 'Show', allergy_type %></td>
    <td><%= link_to 'Edit', edit_allergy_type_path(allergy_type) %></td>
    <td><%= link_to 'Destroy', allergy_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Allergy type', new_allergy_type_path %>

app/views/allergy_types/new.html.erb
<h1>New allergy_type</h1>

<%= render 'form' %>

<%= link_to 'Back', allergy_types_path %>

app/views/allergy_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @allergy_type.name %>
</p>

<p>
  <b>Description:</b>
  <%= @allergy_type.description %>
</p>


<%= link_to 'Edit', edit_allergy_type_path(@allergy_type) %> |
<%= link_to 'Back', allergy_types_path %>