config/routes.rb
CantinhoDoAlergico::Application.routes.draw do
  resources :products

  resources :send_types

  resources :manufacturers

  resources :intolerance_types

  resources :sub_categories

  resources :categories

  resources :allergy_types

  root :to => 'products#index'

end

app/controllers/intolerance_types_controller.rb
class IntoleranceTypesController < ApplicationController
  # GET /intolerance_types
  # GET /intolerance_types.json
  def index
    @intolerance_types = IntoleranceType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @intolerance_types }
    end
  end

  # GET /intolerance_types/1
  # GET /intolerance_types/1.json
  def show
    @intolerance_type = IntoleranceType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @intolerance_type }
    end
  end

  # GET /intolerance_types/new
  # GET /intolerance_types/new.json
  def new
    @intolerance_type = IntoleranceType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @intolerance_type }
    end
  end

  # GET /intolerance_types/1/edit
  def edit
    @intolerance_type = IntoleranceType.find(params[:id])
  end

  # POST /intolerance_types
  # POST /intolerance_types.json
  def create
    @intolerance_type = IntoleranceType.new(params[:intolerance_type])

    respond_to do |format|
      if @intolerance_type.save
        format.html { redirect_to @intolerance_type, notice: 'Intolerance type was successfully created.' }
        format.json { render json: @intolerance_type, status: :created, location: @intolerance_type }
      else
        format.html { render action: "new" }
        format.json { render json: @intolerance_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /intolerance_types/1
  # PUT /intolerance_types/1.json
  def update
    @intolerance_type = IntoleranceType.find(params[:id])

    respond_to do |format|
      if @intolerance_type.update_attributes(params[:intolerance_type])
        format.html { redirect_to @intolerance_type, notice: 'Intolerance type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @intolerance_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /intolerance_types/1
  # DELETE /intolerance_types/1.json
  def destroy
    @intolerance_type = IntoleranceType.find(params[:id])
    @intolerance_type.destroy

    respond_to do |format|
      format.html { redirect_to intolerance_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/intolerance_types_helper.rb
module IntoleranceTypesHelper
end

app/views/intolerance_types/_form.html.erb
<%= form_for(@intolerance_type) do |f| %>
  <% if @intolerance_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@intolerance_type.errors.count, "error") %> prohibited this intolerance_type from being saved:</h2>

      <ul>
      <% @intolerance_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/intolerance_types/edit.html.erb
<h1>Editing intolerance_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @intolerance_type %> |
<%= link_to 'Back', intolerance_types_path %>

app/views/intolerance_types/index.html.erb
<h1>Listing intolerance_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @intolerance_types.each do |intolerance_type| %>
  <tr>
    <td><%= intolerance_type.name %></td>
    <td><%= intolerance_type.description %></td>
    <td><%= link_to 'Show', intolerance_type %></td>
    <td><%= link_to 'Edit', edit_intolerance_type_path(intolerance_type) %></td>
    <td><%= link_to 'Destroy', intolerance_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Intolerance type', new_intolerance_type_path %>

app/views/intolerance_types/new.html.erb
<h1>New intolerance_type</h1>

<%= render 'form' %>

<%= link_to 'Back', intolerance_types_path %>

app/views/intolerance_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @intolerance_type.name %>
</p>

<p>
  <b>Description:</b>
  <%= @intolerance_type.description %>
</p>


<%= link_to 'Edit', edit_intolerance_type_path(@intolerance_type) %> |
<%= link_to 'Back', intolerance_types_path %>